# Generated by Django 3.1 on 2020-08-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200818_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
