# Generated by Django 3.1 on 2020-08-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_posts_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='view',
            new_name='public_view',
        ),
    ]
